// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "cloud-native/api/models"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: user
func (_m *UserService) CreateAccount(user *models.CreateUserRequest) (string, *models.Error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.CreateUserRequest) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *models.Error
	if rf, ok := ret.Get(1).(func(*models.CreateUserRequest) *models.Error); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: userId
func (_m *UserService) GetUserById(userId string) (*models.User, *models.Error) {
	ret := _m.Called(userId)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 *models.Error
	if rf, ok := ret.Get(1).(func(string) *models.Error); ok {
		r1 = rf(userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}

	return r0, r1
}
